---
# tasks file for pm2

- name: check if pm2 exists
  stat:
    path: /usr/bin/pm2
  register: pm2_exists

- name: Install pm2
  npm:
    name: pm2
    global: yes
  become: yes
  when: not pm2_exists.stat.exists
  register: task_result
  until: task_result is success
  retries: 3
  delay: 2

- name: Symlink into /usr/bin
  file: >
    src={{ node_home }}/lib/node_modules/pm2/bin/{{ item }}
    dest=/usr/bin/{{ item }}
    state=link
  with_items:
    - pm2

- name: Init config command
  shell: "PATH=$PATH:/usr/local/node/bin /usr/bin/pm2 startup systemd -u {{ app_user }} --hp {{ app_folder }} --service-name {{ app_name }}"
